[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pump_raydium = "BjcqoRYZuWuGu5nHSrEyi5DFZKg51xNSP9RP7nEYp75j"

[programs.localnet]
pump_raydium = "BjcqoRYZuWuGu5nHSrEyi5DFZKg51xNSP9RP7nEYp75j"

[programs.mainnet]
pump_raydium = "BjcqoRYZuWuGu5nHSrEyi5DFZKg51xNSP9RP7nEYp75j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://meriel-0exl8k-fast-mainnet.helius-rpc.com"
wallet = "./keys/admin.json"

[scripts]
build = "rm -rf target && anchor build && mkdir -p target/deploy && cp ./keys/program/*.json ./target/deploy/pump_raydium-keypair.json"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
